# Numpy array over python list

In [1]:
import numpy as np

In [4]:
my_list = range(10000)

In [3]:
my_array = np.arange(10000)

check the runtime of the list

In [5]:
%timeit [i**2 for i in my_list]

3.17 ms ± 183 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
check the runtime of the numpy array

In [6]:
%timeit my_array**2

6.77 µs ± 73.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
my_array

array([   0,    1,    2, ..., 9997, 9998, 9999])

Some methods that you can use on numpy array

In [11]:
#check array dimension
my_array.ndim

1

In [9]:
#check array shape of matrix
my_array.shape

(10000,)

In [12]:
#size or lenght of the array
my_array.size

10000

In [17]:
#data type contained in the array
my_array.dtype

dtype('int32')

In [18]:
"""creatring an array in python
    ->assign ito a variable
    ->call np.array method
    ->pass the list inside the above method"""

new_array = np.array([1,2,3,4])

In [19]:
new_array

array([1, 2, 3, 4])

In [21]:
ml = [4,3,2,1]
nw_array =  np.array(ml)

In [22]:
nw_array

array([4, 3, 2, 1])

In [25]:
#when looking for methods that have a vertain feature
np.lookfor('linspace')

Search results for 'linspace'
-----------------------------
numpy.linspace
    Return evenly spaced numbers over a specified interval.
numpy.abs
    Calculate the absolute value element-wise.
numpy.exp
    Calculate the exponential of all elements in the input array.
numpy.sin
    Trigonometric sine, element-wise.
numpy.cosh
    Hyperbolic cosine, element-wise.
numpy.sinc
    Return the sinc function.
numpy.outer
    Compute the outer product of two vectors.
numpy.arange
    Return evenly spaced values within a given interval.
numpy.arccos
    Trigonometric inverse cosine, element-wise.
numpy.arctan
    Trigonometric inverse tangent, element-wise.
numpy.interp
    One-dimensional linear interpolation.
numpy.kaiser
    Return the Kaiser window.
numpy.unwrap
    Unwrap by changing deltas between values to 2*pi complement.
numpy.hamming
    Return the Hamming window.
numpy.hanning
    Return the Hanning window.
numpy.polyfit
    Least squares polynomial fit.
numpy.bartlett
    Return the 

In [26]:
#looking for a method but you don't know the full name
np.h*?

In [27]:
#find out how a methoid works get its documentation
np.histogram?

displaying an image as an array on jupyter

In [30]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline

In [31]:
coding = mpimg.imread('coding.png')

In [32]:
coding

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)